### ISSUE TITLE
Offthread loading?

### ISSUE THREAD

**Issue by wcandillon** [hirbod/expo-video-metadata#2]
Hello @hirbod :)

Small question, in React Native Skia we are considering loading the metadata on a dedicated thread as getting metadata from a slow network file, will block the UI thread substantially. Is that something you are experiencing as well?

**Comment by hirbod** [comment]
Hi @wcandillon,

I haven't tested this case, but I can imagine this problem might occur here as well.

Most of my tests were for local files (e.g., before uploading videos to the server). Remote support was a last-minute addition, so not all edge cases were tested. I'll verify it—offloading to a separate thread makes sense.

**Comment by wcandillon** [comment]
in our case we ended up using a dedicated reanimated thread for this: https://github.com/Shopify/react-native-skia/pull/2473/files#diff-3fa513fa42d43a21675b46978137d3e215abb8d4c245fdce1f5f61b49ff55d0fR62
but this would only work for JSI

**Comment by hirbod** [comment]
Oh, interesting. I thought you’d wrap the AV/native part in some DispatchQueue.main.async instead. (Swift example)
I'll definitely look into this for this library soon. Thanks for the insights.

**Comment by wcandillon** [comment]
In your case that would make perfect sense. Here because we use JSI it felt a bit too cumbersome.

**Comment by hirbod** [comment]
@wcandillon, I just checked this case today and it seems like my library was unaffected by this, as we're using an AsyncFunction that's already on a separate thread. So, it's non-blocking. Thanks again for raising this issue; it helped me understand these internals a bit better now too.

```swift
AsyncFunction("getVideoInfo", getVideoInfo).runOnQueue(.main)
```
